import st

def connect_to_mysql():
    connection = mysql.connector.connect(
        host=st.environ['localhost'],
        user=st.environ['root'],
        password=st.environ['mysql'],
        database=st.environ['alfaz']
    )
    return connection
